# syntax=docker/dockerfile:1.7
FROM node:24-alpine

WORKDIR /workspace

RUN npm install -g npm@12.0.1

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN npm install --legacy-peer-deps --no-update-notifier --force

COPY . .

CMD ["npm", "run", "dev"]
